import { ExportTemplate } from "./types";

export const edpbRegulator: ExportTemplate = {
  id: "edpb-regulator",
  name: "Regulator View — EDPB DPIA Template",
  description: "Structured per WP248 rev.01 and aligned to EDPB Opinion 28/2024 on AI models.",
  audience: "Supervisory Authority / DPA",
  render: ({ assessment, threats }) => {
    const d = (assessment.details ?? {}) as Record<string, unknown>;
    const v = (k: string) => (d[k] ? String(d[k]) : "Not specified");
    const list = (k: string) => {
      const x = d[k];
      if (Array.isArray(x)) return x.map((i) => `- ${String(i)}`).join("\n");
      return "- Not specified";
    };
    const threatLines = threats.length
      ? threats.map((t) => `- **${t.lens} / ${t.id}** — ${t.label}: ${t.detail}`).join("\n")
      : "- No structured threat register attached.";

    return `# DPIA — Regulator Submission

**Template:** EDPB / WP248 rev.01, aligned to EDPB Opinion 28/2024 (AI models)
**Reference:** ${assessment.id}
**Processing name:** ${assessment.name}
**Controller / Owner:** ${assessment.owner}
**Date of assessment:** ${assessment.date}
**Risk tier:** ${assessment.tier} (score ${assessment.riskScore}, level ${assessment.riskLevel})

---

## 1. Systematic description of the processing

**Nature, scope, context and purposes**
- Category: ${assessment.category}
- Processing type: ${v("processingType")}
- Business justification / purpose: ${v("businessJustification")}

**Data categories processed**
${list("dataCategories")}

**Legal basis (Art. 6 / Art. 9 GDPR)**
- ${v("legalBasis")}

## 2. Necessity and proportionality

- Lawful basis confirmed and documented above.
- Purpose limitation: processing is bound to the stated purpose; no incompatible secondary use without re-assessment.
- Data minimisation: only the categories listed in §1 are processed.
- Storage limitation and retention: per controller retention schedule referenced in safeguards.
- Information to data subjects and rights handling: standard GDPR Art. 13–22 procedures apply.

## 3. Risks to the rights and freedoms of data subjects

${threatLines}

## 4. Measures envisaged to address the risks

- Technical & organisational safeguards: ${v("safeguards")}
- Human oversight: ${v("oversight")}
- Re-assessment trigger: material change to model, data, vendor, or purpose.

## 5. EDPB Opinion 28/2024 — AI model considerations

- Anonymity of model: assessed against memorisation and inference risks documented in §3.
- Legitimate interest test (where applicable): purpose, necessity, balancing recorded in §1–§2.
- Consequences of unlawful processing in training: documented mitigation in §4.

## 6. Sign-off

| Role | Name | Date | Signature |
|---|---|---|---|
| Data Protection Officer | | | |
| Controller representative | | | |
| Information Security | | | |

_Generated by Priveria. Submit to the competent Supervisory Authority where prior consultation is required (GDPR Art. 36)._
`;
  },
};
