import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // "dist" is build output; the mcp edge function is an auto-generated bundle
  // (regenerated by the @lovable.dev/mcp-js Vite plugin) and must not be linted.
  { ignores: ["dist", "supabase/functions/mcp/index.ts"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // shadcn/ui generated files and context files mix exports by design
    files: ["src/components/ui/**", "src/components/enterprise/**", "src/contexts/**", "src/config/features.ts"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
);
