// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/list-assessments.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-assessments.ts
var list_assessments_default = defineTool({
  name: "list_assessments",
  title: "List DPIA assessments",
  description: "List the signed-in user's DPIA / AI risk assessments with status, risk score, and risk level.",
  inputSchema: {
    status: z.string().optional().describe("Optional status filter, e.g. draft, in_review, completed."),
    limit: z.number().int().optional().describe("Maximum number of assessments to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("assessments").select("id, display_id, name, category, status, risk_level, risk_score, tier, owner, next_review, updated_at").order("updated_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 25, 1), 100));
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { assessments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-assessment.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_assessment_default = defineTool2({
  name: "get_assessment",
  title: "Get DPIA assessment",
  description: "Fetch one DPIA assessment in full, including processing details, data categories, legal basis, and the stored risk/threat details payload.",
  inputSchema: {
    id: z2.string().describe("Assessment UUID, or the human-readable display id (e.g. DPIA-001).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);
    const { data, error } = await supabase.from("assessments").select("*").eq(isUuid ? "id" : "display_id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No assessment found for "${id}".` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { assessment: data }
    };
  }
});

// src/lib/mcp/tools/create-assessment.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_assessment_default = defineTool3({
  name: "create_assessment",
  title: "Create DPIA assessment",
  description: "Create a new DPIA / AI risk assessment for the signed-in user. Use for intake; refine details later in the Priveria wizard.",
  inputSchema: {
    name: z3.string().trim().min(1).describe("Name of the system or processing activity."),
    category: z3.string().trim().min(1).describe("Assessment category, e.g. AI System, Vendor, Product."),
    processing_purpose: z3.string().optional().describe("Why the personal data is processed."),
    processing_type: z3.string().optional().describe("Processing type, e.g. Product/Application."),
    legal_basis: z3.string().optional().describe("GDPR legal basis, e.g. Consent, Legitimate Interests."),
    data_categories: z3.array(z3.string()).optional().describe("Categories of personal data processed."),
    retention_period: z3.string().optional().describe("Retention period for the data."),
    owner: z3.string().optional().describe("Accountable owner for this assessment."),
    risk_score: z3.number().optional().describe("Initial risk score 0-100."),
    risk_level: z3.string().optional().describe("Initial risk level: low, medium, high, or critical."),
    status: z3.string().optional().describe("Initial status, defaults to draft.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("assessments").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      category: input.category,
      processing_purpose: input.processing_purpose ?? null,
      processing_type: input.processing_type ?? null,
      legal_basis: input.legal_basis ?? null,
      data_categories: input.data_categories ?? null,
      retention_period: input.retention_period ?? null,
      owner: input.owner ?? null,
      risk_score: input.risk_score ?? 0,
      risk_level: input.risk_level ?? "low",
      status: input.status ?? "draft",
      details: {}
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { assessment: data }
    };
  }
});

// src/lib/mcp/tools/list-vendors.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_vendors_default = defineTool4({
  name: "list_vendors",
  title: "List third-party vendors",
  description: "List the signed-in user's third-party vendors with risk level, compliance status, jurisdiction, and certifications.",
  inputSchema: {
    risk_level: z4.string().optional().describe("Optional risk level filter: low, medium, high, critical."),
    limit: z4.number().int().optional().describe("Maximum number of vendors to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ risk_level, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("vendors").select("id, name, category, risk_level, compliance_status, jurisdiction, data_processing, certifications, updated_at").order("updated_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 25, 1), 100));
    if (risk_level) query = query.eq("risk_level", risk_level);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { vendors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/summarize-risk-posture.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.1";
var summarize_risk_posture_default = defineTool5({
  name: "summarize_risk_posture",
  title: "Summarize privacy risk posture",
  description: "Aggregate the signed-in user's assessments and vendors into a portfolio risk snapshot: counts by status, risk level, average risk score, and high-risk items needing attention.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const [assessmentsRes, vendorsRes] = await Promise.all([
      supabase.from("assessments").select("name, display_id, status, risk_level, risk_score, next_review"),
      supabase.from("vendors").select("name, risk_level, compliance_status")
    ]);
    if (assessmentsRes.error) {
      return { content: [{ type: "text", text: assessmentsRes.error.message }], isError: true };
    }
    if (vendorsRes.error) {
      return { content: [{ type: "text", text: vendorsRes.error.message }], isError: true };
    }
    const assessments = assessmentsRes.data ?? [];
    const vendors = vendorsRes.data ?? [];
    const tally = (rows, key) => rows.reduce((acc, row) => {
      const value = String(row[key] ?? "unknown");
      acc[value] = (acc[value] ?? 0) + 1;
      return acc;
    }, {});
    const averageRiskScore = assessments.length ? Math.round(
      assessments.reduce((sum, a) => sum + (Number(a.risk_score) || 0), 0) / assessments.length
    ) : 0;
    const summary = {
      assessments: {
        total: assessments.length,
        byStatus: tally(assessments, "status"),
        byRiskLevel: tally(assessments, "risk_level"),
        averageRiskScore,
        highRisk: assessments.filter((a) => ["high", "critical"].includes(String(a.risk_level).toLowerCase())).map((a) => ({
          name: a.name,
          displayId: a.display_id,
          riskLevel: a.risk_level,
          riskScore: a.risk_score,
          nextReview: a.next_review
        }))
      },
      vendors: {
        total: vendors.length,
        byRiskLevel: tally(vendors, "risk_level"),
        byComplianceStatus: tally(vendors, "compliance_status")
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/sync-assessment-to-onetrust.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z5 } from "npm:zod@^3.25.76";
function env(name) {
  const runtime = globalThis;
  return (runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name])?.trim() || void 0;
}
var RISK_MAP = {
  low: "Low",
  medium: "Medium",
  high: "High",
  critical: "Very High"
};
var STATUS_MAP = {
  draft: "In Progress",
  in_review: "In Review",
  "in-review": "In Review",
  review: "In Review",
  completed: "Completed",
  approved: "Approved",
  archived: "Archived"
};
function mapToOneTrust(assessment) {
  const details = assessment.details ?? {};
  const risks = Array.isArray(details.risks) ? details.risks : [];
  return {
    assessment: {
      name: assessment.name,
      externalId: assessment.display_id ?? assessment.id,
      templateType: "DPIA",
      status: STATUS_MAP[String(assessment.status).toLowerCase()] ?? "In Progress",
      residualRiskLevel: RISK_MAP[String(assessment.risk_level).toLowerCase()] ?? "Unknown",
      riskScore: assessment.risk_score ?? 0,
      owner: assessment.owner ?? null,
      nextReviewDate: assessment.next_review ?? null
    },
    processingActivity: {
      purpose: assessment.processing_purpose ?? null,
      processingType: assessment.processing_type ?? null,
      lawfulBasis: assessment.legal_basis ?? null,
      retentionPeriod: assessment.retention_period ?? null,
      personalDataCategories: assessment.data_categories ?? []
    },
    risks: risks.map((risk, index) => ({
      externalId: risk.id ?? `${assessment.display_id ?? assessment.id}-R${index + 1}`,
      name: risk.title ?? risk.name ?? `Risk ${index + 1}`,
      description: risk.description ?? null,
      likelihood: risk.likelihood ?? null,
      impact: risk.impact ?? null,
      treatment: risk.mitigation ?? risk.treatment ?? null
    })),
    fieldMappings: [
      { priveria: "name", oneTrust: "assessment.name" },
      { priveria: "display_id", oneTrust: "assessment.externalId" },
      { priveria: "status", oneTrust: "assessment.status" },
      { priveria: "risk_level", oneTrust: "assessment.residualRiskLevel" },
      { priveria: "risk_score", oneTrust: "assessment.riskScore" },
      { priveria: "processing_purpose", oneTrust: "processingActivity.purpose" },
      { priveria: "legal_basis", oneTrust: "processingActivity.lawfulBasis" },
      { priveria: "data_categories", oneTrust: "processingActivity.personalDataCategories" },
      { priveria: "retention_period", oneTrust: "processingActivity.retentionPeriod" },
      { priveria: "details.risks[]", oneTrust: "risks[]" }
    ]
  };
}
var sync_assessment_to_onetrust_default = defineTool6({
  name: "sync_assessment_to_onetrust",
  title: "Sync assessment to OneTrust",
  description: "Trigger the OneTrust GRC integration for one DPIA assessment. Maps the Priveria assessment onto the OneTrust DPIA/processing-activity schema, pushes it when OneTrust credentials are configured, and returns sync status plus the field mapping results. Use dry_run to preview the mapping without calling OneTrust.",
  inputSchema: {
    assessment_id: z5.string().describe("Assessment UUID or human-readable display id (e.g. DPIA-001) to sync."),
    dry_run: z5.boolean().optional().describe("When true, only compute and return the mapping without pushing to OneTrust.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ assessment_id, dry_run }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
      assessment_id
    );
    const { data: assessment, error } = await supabase.from("assessments").select("*").eq(isUuid ? "id" : "display_id", assessment_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!assessment) {
      return {
        content: [{ type: "text", text: `No assessment found for "${assessment_id}".` }],
        isError: true
      };
    }
    const mapping = mapToOneTrust(assessment);
    const syncedAt = (/* @__PURE__ */ new Date()).toISOString();
    const apiKey = env("ONETRUST_API_KEY");
    const orgId = env("ONETRUST_ORG_ID");
    const baseUrl = (env("ONETRUST_BASE_URL") ?? "https://app.onetrust.com/api").replace(/\/+$/, "");
    if (dry_run || !apiKey) {
      const result2 = {
        assessmentId: assessment.id,
        displayId: assessment.display_id,
        syncStatus: dry_run ? "dry_run" : "not_configured",
        syncedAt,
        message: dry_run ? "Mapping computed. No data was sent to OneTrust." : "OneTrust credentials are not configured for this workspace (ONETRUST_API_KEY missing). Returned the mapping that would be pushed.",
        target: { baseUrl, organizationId: orgId ?? null },
        mapping
      };
      return {
        content: [{ type: "text", text: JSON.stringify(result2, null, 2) }],
        structuredContent: result2
      };
    }
    let syncStatus = "failed";
    let remoteId = null;
    let message = "";
    let httpStatus = null;
    try {
      const response = await fetch(`${baseUrl}/privacy/v2/assessments`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
          ...orgId ? { "X-Organization-Id": orgId } : {}
        },
        body: JSON.stringify(mapping)
      });
      httpStatus = response.status;
      const bodyText = await response.text();
      if (response.ok) {
        syncStatus = "synced";
        try {
          const parsed = JSON.parse(bodyText);
          remoteId = parsed?.id ?? parsed?.assessmentId ?? null;
        } catch {
          remoteId = null;
        }
        message = "Assessment pushed to OneTrust successfully.";
      } else {
        message = `OneTrust rejected the sync [${response.status}]: ${bodyText.slice(0, 500)}`;
      }
    } catch (fetchError) {
      message = `OneTrust request failed: ${fetchError instanceof Error ? fetchError.message : String(fetchError)}`;
    }
    const details = assessment.details ?? {};
    const nextDetails = {
      ...details,
      integrations: {
        ...details.integrations ?? {},
        onetrust: {
          syncStatus,
          syncedAt,
          remoteId,
          message,
          httpStatus
        }
      }
    };
    const { error: updateError } = await supabase.from("assessments").update({ details: nextDetails }).eq("id", assessment.id);
    const result = {
      assessmentId: assessment.id,
      displayId: assessment.display_id,
      syncStatus,
      syncedAt,
      httpStatus,
      remoteId,
      message,
      persisted: !updateError,
      persistError: updateError?.message ?? null,
      target: { baseUrl, organizationId: orgId ?? null },
      mapping
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result,
      isError: syncStatus === "failed"
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jbazqemqvbmusqdqxkeu";
var mcp_default = defineMcp({
  name: "priveria",
  title: "priveria",
  version: "0.1.0",
  instructions: "Privacy governance tools for Priveria. Use `list_assessments` and `get_assessment` to read DPIA / AI risk assessments, `create_assessment` to start a new intake, `list_vendors` for third-party risk, `summarize_risk_posture` for a portfolio-level privacy risk snapshot, and `sync_assessment_to_onetrust` to push an assessment to OneTrust and get sync status plus field mapping results. All tools act as the signed-in Priveria user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_assessments_default,
    get_assessment_default,
    create_assessment_default,
    list_vendors_default,
    summarize_risk_posture_default,
    sync_assessment_to_onetrust_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
