// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/list-assessments.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-assessments.ts
var list_assessments_default = defineTool({
  name: "list_assessments",
  title: "List DPIA assessments",
  description: "List the signed-in user's DPIA / AI risk assessments with status, risk score, and risk level.",
  inputSchema: {
    status: z.string().optional().describe("Optional status filter, e.g. draft, in_review, completed."),
    limit: z.number().int().optional().describe("Maximum number of assessments to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("assessments").select("id, display_id, name, category, status, risk_level, risk_score, tier, owner, next_review, updated_at").order("updated_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 25, 1), 100));
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { assessments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-assessment.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_assessment_default = defineTool2({
  name: "get_assessment",
  title: "Get DPIA assessment",
  description: "Fetch one DPIA assessment in full, including processing details, data categories, legal basis, and the stored risk/threat details payload.",
  inputSchema: {
    id: z2.string().describe("Assessment UUID, or the human-readable display id (e.g. DPIA-001).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);
    const { data, error } = await supabase.from("assessments").select("*").eq(isUuid ? "id" : "display_id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No assessment found for "${id}".` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { assessment: data }
    };
  }
});

// src/lib/mcp/tools/create-assessment.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_assessment_default = defineTool3({
  name: "create_assessment",
  title: "Create DPIA assessment",
  description: "Create a new DPIA / AI risk assessment for the signed-in user. Use for intake; refine details later in the Priveria wizard.",
  inputSchema: {
    name: z3.string().trim().min(1).describe("Name of the system or processing activity."),
    category: z3.string().trim().min(1).describe("Assessment category, e.g. AI System, Vendor, Product."),
    processing_purpose: z3.string().optional().describe("Why the personal data is processed."),
    processing_type: z3.string().optional().describe("Processing type, e.g. Product/Application."),
    legal_basis: z3.string().optional().describe("GDPR legal basis, e.g. Consent, Legitimate Interests."),
    data_categories: z3.array(z3.string()).optional().describe("Categories of personal data processed."),
    retention_period: z3.string().optional().describe("Retention period for the data."),
    owner: z3.string().optional().describe("Accountable owner for this assessment."),
    risk_score: z3.number().optional().describe("Initial risk score 0-100."),
    risk_level: z3.string().optional().describe("Initial risk level: low, medium, high, or critical."),
    status: z3.string().optional().describe("Initial status, defaults to draft.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("assessments").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      category: input.category,
      processing_purpose: input.processing_purpose ?? null,
      processing_type: input.processing_type ?? null,
      legal_basis: input.legal_basis ?? null,
      data_categories: input.data_categories ?? null,
      retention_period: input.retention_period ?? null,
      owner: input.owner ?? null,
      risk_score: input.risk_score ?? 0,
      risk_level: input.risk_level ?? "low",
      status: input.status ?? "draft",
      details: {}
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { assessment: data }
    };
  }
});

// src/lib/mcp/tools/list-vendors.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_vendors_default = defineTool4({
  name: "list_vendors",
  title: "List third-party vendors",
  description: "List the signed-in user's third-party vendors with risk level, compliance status, jurisdiction, and certifications.",
  inputSchema: {
    risk_level: z4.string().optional().describe("Optional risk level filter: low, medium, high, critical."),
    limit: z4.number().int().optional().describe("Maximum number of vendors to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ risk_level, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("vendors").select("id, name, category, risk_level, compliance_status, jurisdiction, data_processing, certifications, updated_at").order("updated_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 25, 1), 100));
    if (risk_level) query = query.eq("risk_level", risk_level);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { vendors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/summarize-risk-posture.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.1";
var summarize_risk_posture_default = defineTool5({
  name: "summarize_risk_posture",
  title: "Summarize privacy risk posture",
  description: "Aggregate the signed-in user's assessments and vendors into a portfolio risk snapshot: counts by status, risk level, average risk score, and high-risk items needing attention.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const [assessmentsRes, vendorsRes] = await Promise.all([
      supabase.from("assessments").select("name, display_id, status, risk_level, risk_score, next_review"),
      supabase.from("vendors").select("name, risk_level, compliance_status")
    ]);
    if (assessmentsRes.error) {
      return { content: [{ type: "text", text: assessmentsRes.error.message }], isError: true };
    }
    if (vendorsRes.error) {
      return { content: [{ type: "text", text: vendorsRes.error.message }], isError: true };
    }
    const assessments = assessmentsRes.data ?? [];
    const vendors = vendorsRes.data ?? [];
    const tally = (rows, key) => rows.reduce((acc, row) => {
      const value = String(row[key] ?? "unknown");
      acc[value] = (acc[value] ?? 0) + 1;
      return acc;
    }, {});
    const averageRiskScore = assessments.length ? Math.round(
      assessments.reduce((sum, a) => sum + (Number(a.risk_score) || 0), 0) / assessments.length
    ) : 0;
    const summary = {
      assessments: {
        total: assessments.length,
        byStatus: tally(assessments, "status"),
        byRiskLevel: tally(assessments, "risk_level"),
        averageRiskScore,
        highRisk: assessments.filter((a) => ["high", "critical"].includes(String(a.risk_level).toLowerCase())).map((a) => ({
          name: a.name,
          displayId: a.display_id,
          riskLevel: a.risk_level,
          riskScore: a.risk_score,
          nextReview: a.next_review
        }))
      },
      vendors: {
        total: vendors.length,
        byRiskLevel: tally(vendors, "risk_level"),
        byComplianceStatus: tally(vendors, "compliance_status")
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jbazqemqvbmusqdqxkeu";
var mcp_default = defineMcp({
  name: "priveria",
  title: "priveria",
  version: "0.1.0",
  instructions: "Privacy governance tools for Priveria. Use `list_assessments` and `get_assessment` to read DPIA / AI risk assessments, `create_assessment` to start a new intake, `list_vendors` for third-party risk, and `summarize_risk_posture` for a portfolio-level privacy risk snapshot. All tools act as the signed-in Priveria user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_assessments_default,
    get_assessment_default,
    create_assessment_default,
    list_vendors_default,
    summarize_risk_posture_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
